/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-12 at 04:39:05 UTC 
 * Modify at your own risk.
 */

package mx.jtails.homelike.api.model;

/**
 * Model definition for DetallePedido.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pedidoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class DetallePedido extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer cantidad;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idDetallePedido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Pedido pedido;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Producto producto;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getCantidad() {
    return cantidad;
  }

  /**
   * @param cantidad cantidad or {@code null} for none
   */
  public DetallePedido setCantidad(java.lang.Integer cantidad) {
    this.cantidad = cantidad;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdDetallePedido() {
    return idDetallePedido;
  }

  /**
   * @param idDetallePedido idDetallePedido or {@code null} for none
   */
  public DetallePedido setIdDetallePedido(java.lang.Integer idDetallePedido) {
    this.idDetallePedido = idDetallePedido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Pedido getPedido() {
    return pedido;
  }

  /**
   * @param pedido pedido or {@code null} for none
   */
  public DetallePedido setPedido(Pedido pedido) {
    this.pedido = pedido;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Producto getProducto() {
    return producto;
  }

  /**
   * @param producto producto or {@code null} for none
   */
  public DetallePedido setProducto(Producto producto) {
    this.producto = producto;
    return this;
  }

  @Override
  public DetallePedido set(String fieldName, Object value) {
    return (DetallePedido) super.set(fieldName, value);
  }

  @Override
  public DetallePedido clone() {
    return (DetallePedido) super.clone();
  }

}
