/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-09-17 at 04:39:09 UTC 
 * Modify at your own risk.
 */

package mx.jtails.homelike.api.model;

/**
 * Model definition for Direccion.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the pedidoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Direccion extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calle;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calle1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String calle2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String colonia;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String cp;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Cuenta cuenta;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String delegacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer esDefault;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String estado;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private com.google.api.client.util.DateTime fechaHoraCreacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idDireccion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String latitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String longitud;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nexterior;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ninterior;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pais;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String referencia1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String referencia2;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalle() {
    return calle;
  }

  /**
   * @param calle calle or {@code null} for none
   */
  public Direccion setCalle(java.lang.String calle) {
    this.calle = calle;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalle1() {
    return calle1;
  }

  /**
   * @param calle1 calle1 or {@code null} for none
   */
  public Direccion setCalle1(java.lang.String calle1) {
    this.calle1 = calle1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCalle2() {
    return calle2;
  }

  /**
   * @param calle2 calle2 or {@code null} for none
   */
  public Direccion setCalle2(java.lang.String calle2) {
    this.calle2 = calle2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getColonia() {
    return colonia;
  }

  /**
   * @param colonia colonia or {@code null} for none
   */
  public Direccion setColonia(java.lang.String colonia) {
    this.colonia = colonia;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getCp() {
    return cp;
  }

  /**
   * @param cp cp or {@code null} for none
   */
  public Direccion setCp(java.lang.String cp) {
    this.cp = cp;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Cuenta getCuenta() {
    return cuenta;
  }

  /**
   * @param cuenta cuenta or {@code null} for none
   */
  public Direccion setCuenta(Cuenta cuenta) {
    this.cuenta = cuenta;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDelegacion() {
    return delegacion;
  }

  /**
   * @param delegacion delegacion or {@code null} for none
   */
  public Direccion setDelegacion(java.lang.String delegacion) {
    this.delegacion = delegacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getEsDefault() {
    return esDefault;
  }

  /**
   * @param esDefault esDefault or {@code null} for none
   */
  public Direccion setEsDefault(java.lang.Integer esDefault) {
    this.esDefault = esDefault;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getEstado() {
    return estado;
  }

  /**
   * @param estado estado or {@code null} for none
   */
  public Direccion setEstado(java.lang.String estado) {
    this.estado = estado;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public com.google.api.client.util.DateTime getFechaHoraCreacion() {
    return fechaHoraCreacion;
  }

  /**
   * @param fechaHoraCreacion fechaHoraCreacion or {@code null} for none
   */
  public Direccion setFechaHoraCreacion(com.google.api.client.util.DateTime fechaHoraCreacion) {
    this.fechaHoraCreacion = fechaHoraCreacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdDireccion() {
    return idDireccion;
  }

  /**
   * @param idDireccion idDireccion or {@code null} for none
   */
  public Direccion setIdDireccion(java.lang.Integer idDireccion) {
    this.idDireccion = idDireccion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLatitud() {
    return latitud;
  }

  /**
   * @param latitud latitud or {@code null} for none
   */
  public Direccion setLatitud(java.lang.String latitud) {
    this.latitud = latitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLongitud() {
    return longitud;
  }

  /**
   * @param longitud longitud or {@code null} for none
   */
  public Direccion setLongitud(java.lang.String longitud) {
    this.longitud = longitud;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNexterior() {
    return nexterior;
  }

  /**
   * @param nexterior nexterior or {@code null} for none
   */
  public Direccion setNexterior(java.lang.String nexterior) {
    this.nexterior = nexterior;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNinterior() {
    return ninterior;
  }

  /**
   * @param ninterior ninterior or {@code null} for none
   */
  public Direccion setNinterior(java.lang.String ninterior) {
    this.ninterior = ninterior;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPais() {
    return pais;
  }

  /**
   * @param pais pais or {@code null} for none
   */
  public Direccion setPais(java.lang.String pais) {
    this.pais = pais;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getReferencia1() {
    return referencia1;
  }

  /**
   * @param referencia1 referencia1 or {@code null} for none
   */
  public Direccion setReferencia1(java.lang.String referencia1) {
    this.referencia1 = referencia1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getReferencia2() {
    return referencia2;
  }

  /**
   * @param referencia2 referencia2 or {@code null} for none
   */
  public Direccion setReferencia2(java.lang.String referencia2) {
    this.referencia2 = referencia2;
    return this;
  }

  @Override
  public Direccion set(String fieldName, Object value) {
    return (Direccion) super.set(fieldName, value);
  }

  @Override
  public Direccion clone() {
    return (Direccion) super.clone();
  }

}
