/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-03 at 04:15:11 UTC 
 * Modify at your own risk.
 */

package mx.jtails.homelike.api.endpoint.pedidoendpoint;

/**
 * Service definition for Pedidoendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link PedidoendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Pedidoendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the pedidoendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://steam-form-673.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "pedidoendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Pedidoendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Pedidoendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "countActivePedidosByProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link CountActivePedidosByProveedor#execute()} method to invoke
   * the remote operation.
   *
   * @param content the {@link mx.jtails.homelike.api.model.Proveedor}
   * @return the request
   */
  public CountActivePedidosByProveedor countActivePedidosByProveedor(mx.jtails.homelike.api.model.Proveedor content) throws java.io.IOException {
    CountActivePedidosByProveedor result = new CountActivePedidosByProveedor(content);
    initialize(result);
    return result;
  }

  public class CountActivePedidosByProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.Proveedor> {

    private static final String REST_PATH = "countActivePedidosByProveedor";

    /**
     * Create a request for the method "countActivePedidosByProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link CountActivePedidosByProveedor#execute()} method to invoke
     * the remote operation. <p> {@link CountActivePedidosByProveedor#initialize(com.google.api.client
     * .googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link mx.jtails.homelike.api.model.Proveedor}
     * @since 1.13
     */
    protected CountActivePedidosByProveedor(mx.jtails.homelike.api.model.Proveedor content) {
      super(Pedidoendpoint.this, "POST", REST_PATH, content, mx.jtails.homelike.api.model.Proveedor.class);
    }

    @Override
    public CountActivePedidosByProveedor setAlt(java.lang.String alt) {
      return (CountActivePedidosByProveedor) super.setAlt(alt);
    }

    @Override
    public CountActivePedidosByProveedor setFields(java.lang.String fields) {
      return (CountActivePedidosByProveedor) super.setFields(fields);
    }

    @Override
    public CountActivePedidosByProveedor setKey(java.lang.String key) {
      return (CountActivePedidosByProveedor) super.setKey(key);
    }

    @Override
    public CountActivePedidosByProveedor setOauthToken(java.lang.String oauthToken) {
      return (CountActivePedidosByProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public CountActivePedidosByProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CountActivePedidosByProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CountActivePedidosByProveedor setQuotaUser(java.lang.String quotaUser) {
      return (CountActivePedidosByProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public CountActivePedidosByProveedor setUserIp(java.lang.String userIp) {
      return (CountActivePedidosByProveedor) super.setUserIp(userIp);
    }

    @Override
    public CountActivePedidosByProveedor set(String parameterName, Object value) {
      return (CountActivePedidosByProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "countTotalPedidosByProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link CountTotalPedidosByProveedor#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link mx.jtails.homelike.api.model.Proveedor}
   * @return the request
   */
  public CountTotalPedidosByProveedor countTotalPedidosByProveedor(mx.jtails.homelike.api.model.Proveedor content) throws java.io.IOException {
    CountTotalPedidosByProveedor result = new CountTotalPedidosByProveedor(content);
    initialize(result);
    return result;
  }

  public class CountTotalPedidosByProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.Proveedor> {

    private static final String REST_PATH = "countTotalPedidosByProveedor";

    /**
     * Create a request for the method "countTotalPedidosByProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link CountTotalPedidosByProveedor#execute()} method to invoke
     * the remote operation. <p> {@link CountTotalPedidosByProveedor#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link mx.jtails.homelike.api.model.Proveedor}
     * @since 1.13
     */
    protected CountTotalPedidosByProveedor(mx.jtails.homelike.api.model.Proveedor content) {
      super(Pedidoendpoint.this, "POST", REST_PATH, content, mx.jtails.homelike.api.model.Proveedor.class);
    }

    @Override
    public CountTotalPedidosByProveedor setAlt(java.lang.String alt) {
      return (CountTotalPedidosByProveedor) super.setAlt(alt);
    }

    @Override
    public CountTotalPedidosByProveedor setFields(java.lang.String fields) {
      return (CountTotalPedidosByProveedor) super.setFields(fields);
    }

    @Override
    public CountTotalPedidosByProveedor setKey(java.lang.String key) {
      return (CountTotalPedidosByProveedor) super.setKey(key);
    }

    @Override
    public CountTotalPedidosByProveedor setOauthToken(java.lang.String oauthToken) {
      return (CountTotalPedidosByProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public CountTotalPedidosByProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CountTotalPedidosByProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CountTotalPedidosByProveedor setQuotaUser(java.lang.String quotaUser) {
      return (CountTotalPedidosByProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public CountTotalPedidosByProveedor setUserIp(java.lang.String userIp) {
      return (CountTotalPedidosByProveedor) super.setUserIp(userIp);
    }

    @Override
    public CountTotalPedidosByProveedor set(String parameterName, Object value) {
      return (CountTotalPedidosByProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getComentariosPedidosByProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link GetComentariosPedidosByProveedor#execute()} method to invoke
   * the remote operation.
   *
   * @return the request
   */
  public GetComentariosPedidosByProveedor getComentariosPedidosByProveedor() throws java.io.IOException {
    GetComentariosPedidosByProveedor result = new GetComentariosPedidosByProveedor();
    initialize(result);
    return result;
  }

  public class GetComentariosPedidosByProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.PedidoCollection> {

    private static final String REST_PATH = "getComentariosPedidosByProveedor";

    /**
     * Create a request for the method "getComentariosPedidosByProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link GetComentariosPedidosByProveedor#execute()} method to
     * invoke the remote operation. <p> {@link GetComentariosPedidosByProveedor#initialize(com.google.
     * api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetComentariosPedidosByProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.PedidoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetComentariosPedidosByProveedor setAlt(java.lang.String alt) {
      return (GetComentariosPedidosByProveedor) super.setAlt(alt);
    }

    @Override
    public GetComentariosPedidosByProveedor setFields(java.lang.String fields) {
      return (GetComentariosPedidosByProveedor) super.setFields(fields);
    }

    @Override
    public GetComentariosPedidosByProveedor setKey(java.lang.String key) {
      return (GetComentariosPedidosByProveedor) super.setKey(key);
    }

    @Override
    public GetComentariosPedidosByProveedor setOauthToken(java.lang.String oauthToken) {
      return (GetComentariosPedidosByProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public GetComentariosPedidosByProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetComentariosPedidosByProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetComentariosPedidosByProveedor setQuotaUser(java.lang.String quotaUser) {
      return (GetComentariosPedidosByProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetComentariosPedidosByProveedor setUserIp(java.lang.String userIp) {
      return (GetComentariosPedidosByProveedor) super.setUserIp(userIp);
    }

    @Override
    public GetComentariosPedidosByProveedor set(String parameterName, Object value) {
      return (GetComentariosPedidosByProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getHistoricoGananciaByMesProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link GetHistoricoGananciaByMesProveedor#execute()} method to
   * invoke the remote operation.
   *
   * @return the request
   */
  public GetHistoricoGananciaByMesProveedor getHistoricoGananciaByMesProveedor() throws java.io.IOException {
    GetHistoricoGananciaByMesProveedor result = new GetHistoricoGananciaByMesProveedor();
    initialize(result);
    return result;
  }

  public class GetHistoricoGananciaByMesProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.GraficoCollection> {

    private static final String REST_PATH = "getHistoricoGananciaByMesProveedor";

    /**
     * Create a request for the method "getHistoricoGananciaByMesProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link GetHistoricoGananciaByMesProveedor#execute()} method to
     * invoke the remote operation. <p> {@link GetHistoricoGananciaByMesProveedor#initialize(com.googl
     * e.api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize
     * this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetHistoricoGananciaByMesProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.GraficoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setAlt(java.lang.String alt) {
      return (GetHistoricoGananciaByMesProveedor) super.setAlt(alt);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setFields(java.lang.String fields) {
      return (GetHistoricoGananciaByMesProveedor) super.setFields(fields);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setKey(java.lang.String key) {
      return (GetHistoricoGananciaByMesProveedor) super.setKey(key);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setOauthToken(java.lang.String oauthToken) {
      return (GetHistoricoGananciaByMesProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetHistoricoGananciaByMesProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setQuotaUser(java.lang.String quotaUser) {
      return (GetHistoricoGananciaByMesProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor setUserIp(java.lang.String userIp) {
      return (GetHistoricoGananciaByMesProveedor) super.setUserIp(userIp);
    }

    @Override
    public GetHistoricoGananciaByMesProveedor set(String parameterName, Object value) {
      return (GetHistoricoGananciaByMesProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getHistoricoPedidosByDayProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link GetHistoricoPedidosByDayProveedor#execute()} method to
   * invoke the remote operation.
   *
   * @return the request
   */
  public GetHistoricoPedidosByDayProveedor getHistoricoPedidosByDayProveedor() throws java.io.IOException {
    GetHistoricoPedidosByDayProveedor result = new GetHistoricoPedidosByDayProveedor();
    initialize(result);
    return result;
  }

  public class GetHistoricoPedidosByDayProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.GraficoCollection> {

    private static final String REST_PATH = "getHistoricoPedidosByDayProveedor";

    /**
     * Create a request for the method "getHistoricoPedidosByDayProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link GetHistoricoPedidosByDayProveedor#execute()} method to
     * invoke the remote operation. <p> {@link GetHistoricoPedidosByDayProveedor#initialize(com.google
     * .api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetHistoricoPedidosByDayProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.GraficoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setAlt(java.lang.String alt) {
      return (GetHistoricoPedidosByDayProveedor) super.setAlt(alt);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setFields(java.lang.String fields) {
      return (GetHistoricoPedidosByDayProveedor) super.setFields(fields);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setKey(java.lang.String key) {
      return (GetHistoricoPedidosByDayProveedor) super.setKey(key);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setOauthToken(java.lang.String oauthToken) {
      return (GetHistoricoPedidosByDayProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetHistoricoPedidosByDayProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setQuotaUser(java.lang.String quotaUser) {
      return (GetHistoricoPedidosByDayProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor setUserIp(java.lang.String userIp) {
      return (GetHistoricoPedidosByDayProveedor) super.setUserIp(userIp);
    }

    @Override
    public GetHistoricoPedidosByDayProveedor set(String parameterName, Object value) {
      return (GetHistoricoPedidosByDayProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getHistoricoPedidosByMesProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link GetHistoricoPedidosByMesProveedor#execute()} method to
   * invoke the remote operation.
   *
   * @return the request
   */
  public GetHistoricoPedidosByMesProveedor getHistoricoPedidosByMesProveedor() throws java.io.IOException {
    GetHistoricoPedidosByMesProveedor result = new GetHistoricoPedidosByMesProveedor();
    initialize(result);
    return result;
  }

  public class GetHistoricoPedidosByMesProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.GraficoCollection> {

    private static final String REST_PATH = "getHistoricoPedidosByMesProveedor";

    /**
     * Create a request for the method "getHistoricoPedidosByMesProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link GetHistoricoPedidosByMesProveedor#execute()} method to
     * invoke the remote operation. <p> {@link GetHistoricoPedidosByMesProveedor#initialize(com.google
     * .api.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected GetHistoricoPedidosByMesProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.GraficoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setAlt(java.lang.String alt) {
      return (GetHistoricoPedidosByMesProveedor) super.setAlt(alt);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setFields(java.lang.String fields) {
      return (GetHistoricoPedidosByMesProveedor) super.setFields(fields);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setKey(java.lang.String key) {
      return (GetHistoricoPedidosByMesProveedor) super.setKey(key);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setOauthToken(java.lang.String oauthToken) {
      return (GetHistoricoPedidosByMesProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetHistoricoPedidosByMesProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setQuotaUser(java.lang.String quotaUser) {
      return (GetHistoricoPedidosByMesProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor setUserIp(java.lang.String userIp) {
      return (GetHistoricoPedidosByMesProveedor) super.setUserIp(userIp);
    }

    @Override
    public GetHistoricoPedidosByMesProveedor set(String parameterName, Object value) {
      return (GetHistoricoPedidosByMesProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getPedido".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link GetPedido#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetPedido getPedido(java.lang.Long id) throws java.io.IOException {
    GetPedido result = new GetPedido(id);
    initialize(result);
    return result;
  }

  public class GetPedido extends PedidoendpointRequest<mx.jtails.homelike.api.model.Pedido> {

    private static final String REST_PATH = "pedido/{id}";

    /**
     * Create a request for the method "getPedido".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link GetPedido#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetPedido#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetPedido(java.lang.Long id) {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.Pedido.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetPedido setAlt(java.lang.String alt) {
      return (GetPedido) super.setAlt(alt);
    }

    @Override
    public GetPedido setFields(java.lang.String fields) {
      return (GetPedido) super.setFields(fields);
    }

    @Override
    public GetPedido setKey(java.lang.String key) {
      return (GetPedido) super.setKey(key);
    }

    @Override
    public GetPedido setOauthToken(java.lang.String oauthToken) {
      return (GetPedido) super.setOauthToken(oauthToken);
    }

    @Override
    public GetPedido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetPedido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetPedido setQuotaUser(java.lang.String quotaUser) {
      return (GetPedido) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetPedido setUserIp(java.lang.String userIp) {
      return (GetPedido) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetPedido setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetPedido set(String parameterName, Object value) {
      return (GetPedido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertPedido".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link InsertPedido#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link mx.jtails.homelike.api.model.Pedido}
   * @return the request
   */
  public InsertPedido insertPedido(mx.jtails.homelike.api.model.Pedido content) throws java.io.IOException {
    InsertPedido result = new InsertPedido(content);
    initialize(result);
    return result;
  }

  public class InsertPedido extends PedidoendpointRequest<mx.jtails.homelike.api.model.Pedido> {

    private static final String REST_PATH = "pedido";

    /**
     * Create a request for the method "insertPedido".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link InsertPedido#execute()} method to invoke the remote
     * operation. <p> {@link
     * InsertPedido#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link mx.jtails.homelike.api.model.Pedido}
     * @since 1.13
     */
    protected InsertPedido(mx.jtails.homelike.api.model.Pedido content) {
      super(Pedidoendpoint.this, "POST", REST_PATH, content, mx.jtails.homelike.api.model.Pedido.class);
    }

    @Override
    public InsertPedido setAlt(java.lang.String alt) {
      return (InsertPedido) super.setAlt(alt);
    }

    @Override
    public InsertPedido setFields(java.lang.String fields) {
      return (InsertPedido) super.setFields(fields);
    }

    @Override
    public InsertPedido setKey(java.lang.String key) {
      return (InsertPedido) super.setKey(key);
    }

    @Override
    public InsertPedido setOauthToken(java.lang.String oauthToken) {
      return (InsertPedido) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertPedido setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertPedido) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertPedido setQuotaUser(java.lang.String quotaUser) {
      return (InsertPedido) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertPedido setUserIp(java.lang.String userIp) {
      return (InsertPedido) super.setUserIp(userIp);
    }

    @Override
    public InsertPedido set(String parameterName, Object value) {
      return (InsertPedido) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listHistoricoPedidosByCuenta".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link ListHistoricoPedidosByCuenta#execute()} method to invoke the
   * remote operation.
   *
   * @return the request
   */
  public ListHistoricoPedidosByCuenta listHistoricoPedidosByCuenta() throws java.io.IOException {
    ListHistoricoPedidosByCuenta result = new ListHistoricoPedidosByCuenta();
    initialize(result);
    return result;
  }

  public class ListHistoricoPedidosByCuenta extends PedidoendpointRequest<mx.jtails.homelike.api.model.PedidoCollection> {

    private static final String REST_PATH = "listHistoricoPedidosByCuenta";

    /**
     * Create a request for the method "listHistoricoPedidosByCuenta".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link ListHistoricoPedidosByCuenta#execute()} method to invoke
     * the remote operation. <p> {@link ListHistoricoPedidosByCuenta#initialize(com.google.api.client.
     * googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListHistoricoPedidosByCuenta() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.PedidoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListHistoricoPedidosByCuenta setAlt(java.lang.String alt) {
      return (ListHistoricoPedidosByCuenta) super.setAlt(alt);
    }

    @Override
    public ListHistoricoPedidosByCuenta setFields(java.lang.String fields) {
      return (ListHistoricoPedidosByCuenta) super.setFields(fields);
    }

    @Override
    public ListHistoricoPedidosByCuenta setKey(java.lang.String key) {
      return (ListHistoricoPedidosByCuenta) super.setKey(key);
    }

    @Override
    public ListHistoricoPedidosByCuenta setOauthToken(java.lang.String oauthToken) {
      return (ListHistoricoPedidosByCuenta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListHistoricoPedidosByCuenta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListHistoricoPedidosByCuenta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListHistoricoPedidosByCuenta setQuotaUser(java.lang.String quotaUser) {
      return (ListHistoricoPedidosByCuenta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListHistoricoPedidosByCuenta setUserIp(java.lang.String userIp) {
      return (ListHistoricoPedidosByCuenta) super.setUserIp(userIp);
    }

    @Override
    public ListHistoricoPedidosByCuenta set(String parameterName, Object value) {
      return (ListHistoricoPedidosByCuenta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listHistoricoPedidosByProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link ListHistoricoPedidosByProveedor#execute()} method to invoke
   * the remote operation.
   *
   * @return the request
   */
  public ListHistoricoPedidosByProveedor listHistoricoPedidosByProveedor() throws java.io.IOException {
    ListHistoricoPedidosByProveedor result = new ListHistoricoPedidosByProveedor();
    initialize(result);
    return result;
  }

  public class ListHistoricoPedidosByProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.PedidoCollection> {

    private static final String REST_PATH = "listHistoricoPedidosByProveedor";

    /**
     * Create a request for the method "listHistoricoPedidosByProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link ListHistoricoPedidosByProveedor#execute()} method to
     * invoke the remote operation. <p> {@link ListHistoricoPedidosByProveedor#initialize(com.google.a
     * pi.client.googleapis.services.AbstractGoogleClientRequest)} must be called to initialize this
     * instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListHistoricoPedidosByProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.PedidoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListHistoricoPedidosByProveedor setAlt(java.lang.String alt) {
      return (ListHistoricoPedidosByProveedor) super.setAlt(alt);
    }

    @Override
    public ListHistoricoPedidosByProveedor setFields(java.lang.String fields) {
      return (ListHistoricoPedidosByProveedor) super.setFields(fields);
    }

    @Override
    public ListHistoricoPedidosByProveedor setKey(java.lang.String key) {
      return (ListHistoricoPedidosByProveedor) super.setKey(key);
    }

    @Override
    public ListHistoricoPedidosByProveedor setOauthToken(java.lang.String oauthToken) {
      return (ListHistoricoPedidosByProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public ListHistoricoPedidosByProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListHistoricoPedidosByProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListHistoricoPedidosByProveedor setQuotaUser(java.lang.String quotaUser) {
      return (ListHistoricoPedidosByProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListHistoricoPedidosByProveedor setUserIp(java.lang.String userIp) {
      return (ListHistoricoPedidosByProveedor) super.setUserIp(userIp);
    }

    @Override
    public ListHistoricoPedidosByProveedor set(String parameterName, Object value) {
      return (ListHistoricoPedidosByProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPedidosByCuenta".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link ListPedidosByCuenta#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListPedidosByCuenta listPedidosByCuenta() throws java.io.IOException {
    ListPedidosByCuenta result = new ListPedidosByCuenta();
    initialize(result);
    return result;
  }

  public class ListPedidosByCuenta extends PedidoendpointRequest<mx.jtails.homelike.api.model.PedidoCollection> {

    private static final String REST_PATH = "listPedidosByCuenta";

    /**
     * Create a request for the method "listPedidosByCuenta".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link ListPedidosByCuenta#execute()} method to invoke the remote
     * operation. <p> {@link ListPedidosByCuenta#initialize(com.google.api.client.googleapis.services.
     * AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPedidosByCuenta() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.PedidoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPedidosByCuenta setAlt(java.lang.String alt) {
      return (ListPedidosByCuenta) super.setAlt(alt);
    }

    @Override
    public ListPedidosByCuenta setFields(java.lang.String fields) {
      return (ListPedidosByCuenta) super.setFields(fields);
    }

    @Override
    public ListPedidosByCuenta setKey(java.lang.String key) {
      return (ListPedidosByCuenta) super.setKey(key);
    }

    @Override
    public ListPedidosByCuenta setOauthToken(java.lang.String oauthToken) {
      return (ListPedidosByCuenta) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPedidosByCuenta setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPedidosByCuenta) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPedidosByCuenta setQuotaUser(java.lang.String quotaUser) {
      return (ListPedidosByCuenta) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPedidosByCuenta setUserIp(java.lang.String userIp) {
      return (ListPedidosByCuenta) super.setUserIp(userIp);
    }

    @Override
    public ListPedidosByCuenta set(String parameterName, Object value) {
      return (ListPedidosByCuenta) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listPedidosByProveedor".
   *
   * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
   * optional parameters, call the {@link ListPedidosByProveedor#execute()} method to invoke the
   * remote operation.
   *
   * @return the request
   */
  public ListPedidosByProveedor listPedidosByProveedor() throws java.io.IOException {
    ListPedidosByProveedor result = new ListPedidosByProveedor();
    initialize(result);
    return result;
  }

  public class ListPedidosByProveedor extends PedidoendpointRequest<mx.jtails.homelike.api.model.PedidoCollection> {

    private static final String REST_PATH = "listPedidosByProveedor";

    /**
     * Create a request for the method "listPedidosByProveedor".
     *
     * This request holds the parameters needed by the the pedidoendpoint server.  After setting any
     * optional parameters, call the {@link ListPedidosByProveedor#execute()} method to invoke the
     * remote operation. <p> {@link ListPedidosByProveedor#initialize(com.google.api.client.googleapis
     * .services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListPedidosByProveedor() {
      super(Pedidoendpoint.this, "GET", REST_PATH, null, mx.jtails.homelike.api.model.PedidoCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListPedidosByProveedor setAlt(java.lang.String alt) {
      return (ListPedidosByProveedor) super.setAlt(alt);
    }

    @Override
    public ListPedidosByProveedor setFields(java.lang.String fields) {
      return (ListPedidosByProveedor) super.setFields(fields);
    }

    @Override
    public ListPedidosByProveedor setKey(java.lang.String key) {
      return (ListPedidosByProveedor) super.setKey(key);
    }

    @Override
    public ListPedidosByProveedor setOauthToken(java.lang.String oauthToken) {
      return (ListPedidosByProveedor) super.setOauthToken(oauthToken);
    }

    @Override
    public ListPedidosByProveedor setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListPedidosByProveedor) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListPedidosByProveedor setQuotaUser(java.lang.String quotaUser) {
      return (ListPedidosByProveedor) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListPedidosByProveedor setUserIp(java.lang.String userIp) {
      return (ListPedidosByProveedor) super.setUserIp(userIp);
    }

    @Override
    public ListPedidosByProveedor set(String parameterName, Object value) {
      return (ListPedidosByProveedor) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Pedidoendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Pedidoendpoint}. */
    @Override
    public Pedidoendpoint build() {
      return new Pedidoendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link PedidoendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setPedidoendpointRequestInitializer(
        PedidoendpointRequestInitializer pedidoendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(pedidoendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
