/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-07-22 21:53:01 UTC)
 * on 2014-10-03 at 08:02:53 UTC 
 * Modify at your own risk.
 */

package mx.jtails.provider.homelike.api.model;

/**
 * Model definition for BigInteger.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the tpedidoendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class BigInteger extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer bit;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer lowestSetBit;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getBit() {
    return bit;
  }

  /**
   * @param bit bit or {@code null} for none
   */
  public BigInteger setBit(java.lang.Integer bit) {
    this.bit = bit;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getLowestSetBit() {
    return lowestSetBit;
  }

  /**
   * @param lowestSetBit lowestSetBit or {@code null} for none
   */
  public BigInteger setLowestSetBit(java.lang.Integer lowestSetBit) {
    this.lowestSetBit = lowestSetBit;
    return this;
  }

  @Override
  public BigInteger set(String fieldName, Object value) {
    return (BigInteger) super.set(fieldName, value);
  }

  @Override
  public BigInteger clone() {
    return (BigInteger) super.clone();
  }

}
