/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-10-28 17:08:27 UTC)
 * on 2014-11-06 at 03:34:13 UTC 
 * Modify at your own risk.
 */

package mx.jtails.provider.homelike.api.model;

/**
 * Model definition for CProducto.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the horariosproveedorendpoint. For a detailed explanation
 * see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CProducto extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String descripcion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer idCProducto;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String presentacion;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Servicio servicio;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescripcion() {
    return descripcion;
  }

  /**
   * @param descripcion descripcion or {@code null} for none
   */
  public CProducto setDescripcion(java.lang.String descripcion) {
    this.descripcion = descripcion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getIdCProducto() {
    return idCProducto;
  }

  /**
   * @param idCProducto idCProducto or {@code null} for none
   */
  public CProducto setIdCProducto(java.lang.Integer idCProducto) {
    this.idCProducto = idCProducto;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getPresentacion() {
    return presentacion;
  }

  /**
   * @param presentacion presentacion or {@code null} for none
   */
  public CProducto setPresentacion(java.lang.String presentacion) {
    this.presentacion = presentacion;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Servicio getServicio() {
    return servicio;
  }

  /**
   * @param servicio servicio or {@code null} for none
   */
  public CProducto setServicio(Servicio servicio) {
    this.servicio = servicio;
    return this;
  }

  @Override
  public CProducto set(String fieldName, Object value) {
    return (CProducto) super.set(fieldName, value);
  }

  @Override
  public CProducto clone() {
    return (CProducto) super.clone();
  }

}
